fix: Command variant Help conflicts with auto-generated one
```
thread 'main' panicked at 'Command rusty_ponyo::bot::alias: command name `help` is duplicated', /home/kawak/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/builder/debug_asserts.rs:329:9
```